from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    HealthView,
    ImportQuestionsView,
    ImportStatusView,
    LeaderboardView,
    QuestionImageView,
    LiveCodingMistakesView,
    LiveCodingResultView,
    LiveCodingSessionDetailView,
    LiveCodingStartView,
    LiveCodingSubmitView,
    LiveCodingTaskListView,
    LoginView,
    LogoutView,
    MarkQuestionMasteredView,
    MeView,
    MistakesView,
    ProgressSubjectsView,
    ProgressSummaryView,
    RegisterView,
    SubjectDetailView,
    SubjectListView,
    SubjectTopicsView,
    TestAnswerView,
    TestFinishView,
    TestResultView,
    TestSessionDetailView,
    TestStartView,
)


urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("question-images/<path:image_path>", QuestionImageView.as_view(), name="question-image"),
    path("auth/register/", RegisterView.as_view(), name="auth-register"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("subjects/", SubjectListView.as_view(), name="subjects"),
    path("subjects/<int:pk>/", SubjectDetailView.as_view(), name="subject-detail"),
    path("subjects/<int:pk>/topics/", SubjectTopicsView.as_view(), name="subject-topics"),
    path("tests/start/", TestStartView.as_view(), name="test-start"),
    path("tests/<int:pk>/", TestSessionDetailView.as_view(), name="test-detail"),
    path("tests/<int:pk>/answer/", TestAnswerView.as_view(), name="test-answer"),
    path("tests/<int:pk>/finish/", TestFinishView.as_view(), name="test-finish"),
    path("tests/<int:pk>/result/", TestResultView.as_view(), name="test-result"),
    path("progress/summary/", ProgressSummaryView.as_view(), name="progress-summary"),
    path("progress/subjects/", ProgressSubjectsView.as_view(), name="progress-subjects"),
    path("progress/mistakes/", MistakesView.as_view(), name="progress-mistakes"),
    path("progress/live-coding/mistakes/", LiveCodingMistakesView.as_view(), name="live-coding-mistakes"),
    path("progress/questions/<int:question_id>/mark-mastered/", MarkQuestionMasteredView.as_view(), name="mark-mastered"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("live-coding/tasks/", LiveCodingTaskListView.as_view(), name="live-coding-tasks"),
    path("live-coding/start/", LiveCodingStartView.as_view(), name="live-coding-start"),
    path("live-coding/<int:pk>/", LiveCodingSessionDetailView.as_view(), name="live-coding-detail"),
    path("live-coding/<int:pk>/submit/", LiveCodingSubmitView.as_view(), name="live-coding-submit"),
    path("live-coding/<int:pk>/result/", LiveCodingResultView.as_view(), name="live-coding-result"),
    path("admin/import-questions/", ImportQuestionsView.as_view(), name="admin-import-questions"),
    path("admin/import-status/", ImportStatusView.as_view(), name="admin-import-status"),
]
